### ISSUE TITLE
Narrow Breadcrumb problems 

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#100]
<img width="869" alt="can-define_list_list" src="https://cloud.githubusercontent.com/assets/78602/19018036/7bf909c6-8818-11e6-9490-7612d8e85c27.png">

I think we should hide the breadcrumb part, leave "in this page".

**Comment by justinbmeyer** [comment]
Still present, but not as critical:

![canjs](https://cloud.githubusercontent.com/assets/78602/19240087/6ffbe4ba-8ece-11e6-95f2-5c1015d84ff7.png)

**Comment by tomgreever** [comment]
It's unusual to me that the CanJS logo and the version are in the same column as the left nav. I would expect the Logo and Chat / Forum / Etc to be in one horizontal menu, while Version + breadcrumb are also in one horizontal nav. Doing this would also help with this issue, though it would not completely solve it. But that's only partly related to this issue. 

One way to solve for this would be to remove elements toward the left and/or remove them near the middle and replace with an ellipsis `...` menu that reveals them again. Here's a simple example:
![screen shot 2016-10-13 at 1 18 19 pm](https://cloud.githubusercontent.com/assets/326843/19361275/a41fac88-9147-11e6-87ee-1002e2247aef.png)

**Comment by tomgreever** [comment]
Ok, I think I can solve this with CSS. Will experiment: 
http://codepen.io/anon/pen/dpjoRy

**Comment by tomgreever** [comment]
So I can set a `max-width` percentage of 5% for all the initial links in the breadcrumb, excluding the "current" page and the "in this page" which results in this: 
![screen shot 2016-10-13 at 4 53 05 pm](https://cloud.githubusercontent.com/assets/326843/19368460/b040d460-9165-11e6-817e-efaa609070b1.png)

@justinbmeyer

**Comment by tomgreever** [comment]
I can probably play with it a bit more to have some control over when it does it. Right now it's a fixed 5%, which means it also shows the `...` here even tho there's plenty of space. B/c it's based on viewport width...
![screen shot 2016-10-13 at 4 56 41 pm](https://cloud.githubusercontent.com/assets/326843/19368539/12c142be-9166-11e6-830a-39c11e349ec0.png)

Branch: https://github.com/canjs/bit-docs-html-canjs/tree/truncate-100

**Comment by tomgreever** [comment]
@justinbmeyer I'm not able to do much more with CSS than this, but I'm open to suggestions if someone knows of a better solution. CSS is only based on the viewport (via media queries) or the parent container as a percentage. So it's ignorant of the width. 

My suggestion would be to write some JS that compares the width of the `<ul>` to the width of the parent and it there is less than, say 50px of space - it applies the class `truncate` to one `<li>` at a time until it fits. 

Let me know what you think or if you know of something else I can try.

**Comment by chasenlehara** [comment]
I’m closing this because the black bar has been removed.
