### ISSUE TITLE
Get rid of normalize css request.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#102]
![atm_guide](https://cloud.githubusercontent.com/assets/78602/19023552/8e9e2cc0-88b6-11e6-88d8-b7c11b87275a.png)

**Comment by matthewp** [comment]
Surprisingly `@import "locate://normalize.css/normalize.css";` doesn't work.

**Comment by Rlin415** [comment]
Not an issue anymore I believe?
