### ISSUE TITLE
Scrolling is strange on ipad

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#118]
Scrolling is strange, because you don't see a scroll bar and you can't swipe for scrolling on the iPad. Scrolling sticks always.

**Comment by justinbmeyer** [comment]
I think @matthewp suggested there's a CSS property that can turn this on.

**Comment by garrettreed** [comment]
@justinbmeyer let me know if #132 is what you are looking for. It feels fine to me in simulator, but I don't have a device to test it.
