### ISSUE TITLE
CanJS dropdown isn't working

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#119]
On our other sites, hovering over the logo shows our other projects:

![donejs_-_donejs](https://cloud.githubusercontent.com/assets/78602/19197733/18e3df06-8c81-11e6-8cbe-23540c8289a6.png)

we need to bring this back. Ideally, this should be developed as some package we can use on our other sites.

**Comment by justinbmeyer** [comment]
https://github.com/donejs/donejs/blob/master/docs/theme/templates/layout.mustache#L61

**Comment by justinbmeyer** [comment]
```
{{donejs-dropdown "canjs"}}
```

**Comment by garrettreed** [comment]
@justinbmeyer is this alright for the dropdown?

![screen shot 2016-10-17 at 7 31 36 pm](https://cloud.githubusercontent.com/assets/4079858/19459420/ca454024-94a0-11e6-8f99-3b8b13722f57.png)

**Comment by garrettreed** [comment]
It would be a good idea to merge and close this one.
We can open another issue about moving this to it's own package with an updated priority.
