### ISSUE TITLE
Top menu for H2s

### ISSUE THREAD

**Issue by tomgreever** [canjs/bit-docs-html-canjs#12]
To bring back the H2s at the top of the page, which currently look like this. A plain `ul`
![screen shot 2016-07-01 at 5 28 10 pm](https://cloud.githubusercontent.com/assets/326843/16535911/3a8988ee-3fb1-11e6-87d7-c0c71fbcc78b.png)

I'd like to suggest a container with links to each section. Maybe sorta like this: 
![screen shot 2016-07-01 at 5 32 13 pm](https://cloud.githubusercontent.com/assets/326843/16535969/ccea0074-3fb1-11e6-9285-5ebe59cdac52.png)

## Interactions
- clicking a link scrolls (animates) the user to that section
- as the user scrolls down the page, the options collapse into a menu showing only one item at a time
- as the user scrolls past each section, the title inside the fixed menu changes to the current section
- If the user hovers over the fixed menu, they can choose a different section 

I mocked this up once before, so using that same mockup with our new look - here is a demonstration of how it might behave (not how it would look, necessarily): 
![sticky](https://cloud.githubusercontent.com/assets/326843/16535943/8b01d772-3fb1-11e6-8d64-5f01e351f7b7.gif)

One change I would make from this demo is that the main "CanJS" header wouldn't be fixed / sticky. Only the section menu would fix to the top. 

Here's the prototype: http://share.bitovi.com/5Y7KWQ/#g=1&p=sticky

Thoughts @justinbmeyer ?

**Comment by justinbmeyer** [comment]
Cool

**Comment by tomgreever** [comment]
@justinbmeyer do you want me to go ahead and mock it up in HTML/CSS like this? I can use a static `ul` for now
