### ISSUE TITLE
Design for search and switching to other CanJS versions

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#120]
Eventually, I'd like to have a search bar, and very quickly we need to be able to link or select to other versions.

![canjs](https://cloud.githubusercontent.com/assets/78602/19197609/649a6a4c-8c80-11e6-8f52-eef31ebd825c.png)

There are several options.  

My strong preference is for a __search box__ in position `#3`.  `#5` is the only other possibility, but I don't like it.

For  #__version__, we might be able to:

- sneak it in at `#1`.  
- Put it in the dropdown for #119. (We could have `CanJS 1.0` and `CanJS 2.0` listed).
- Make it part of the breadcrumb `#4`
- Have a dropdown next to the social buttons `#2`.

**Comment by tomgreever** [comment]
@justinbmeyer here is my current thinking / suggestion for this: 
![search](https://cloud.githubusercontent.com/assets/326843/19360613/de2f3acc-9144-11e6-99bf-b53717463ba3.gif)

I was thinking the search results would display as page titles in the left column, allowing the user to quickly navigate through each search result. Of course, we could also go the "traditional" route and have a separate page / view for search results too.

**Comment by justinbmeyer** [comment]
Looks kinda crowded.  I'm not sure why there's `VERSION ## / CanJS / On this page`  Seems like it should go `CanJS ## / On this page`.

> I was thinking the search results would display as page titles in the left column, 

Yes, this is exactly what I had in mind.

**Comment by tomgreever** [comment]
Here's an updated design. Note the input focuses on page load. X appears only if there is text in the input.

![search2](https://cloud.githubusercontent.com/assets/326843/19367982/66deca0e-9163-11e6-9d15-afc4f7633c5b.gif)

**Comment by justinbmeyer** [comment]
So hot.
