### ISSUE TITLE
Handle ajax errors or we can't find the content

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#122]
We should handle things going wrong with our pushstate "hack".

For example, if an ajax request fails, we should update `window.location` to where they were going.

If an ajax request succeeds, but we can't find the `<article>` or other elements we need to update the current content with, we should update `window.location` to where they were going.

**Comment by garrettreed** [comment]
I've added a fallback to reload the page after a failed ajax request or one that cannot match content. That should handle ajax failures and redirect bad paths to a 404.
