### ISSUE TITLE
Can no longer star github projects on homepage

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#125]
![canjs](https://cloud.githubusercontent.com/assets/78602/19241343/d05d31a6-8ed3-11e6-89a7-4e6f370fbb1a.png)

**Comment by garrettreed** [comment]
@justinbmeyer is this referring to mobile?

**Comment by justinbmeyer** [comment]
hmmm, after refreshing, it seems to work ... I wonder if I had an old version.

**Comment by justinbmeyer** [comment]
Ah, it happens when you navigate.
