### ISSUE TITLE
select[multiple] page fails

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#137]
http://localhost:8080/canjs/doc/can-stache-converters.pages.input-checkbox.html

![select_multiple__and_updates_key](https://cloud.githubusercontent.com/assets/78602/19326079/aa49d5c0-908e-11e6-8b7f-179e9e05d92c.png)

There seems to be similar problems with the other "pages" in `can-stache-converters`

**Comment by justinbmeyer** [comment]
this looks like `<select>` isn't escaped properly.

**Comment by garrettreed** [comment]
I believe this broke article signatures:

![screen shot 2016-10-13 at 1 09 52 pm](https://cloud.githubusercontent.com/assets/4079858/19359197/1e5fac6a-9147-11e6-9f5c-629e914384a9.png)
