### ISSUE TITLE
On this page location doesn't move to the right place

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#140]
Broken here:

![todomvc_guide_and_issues_ _canjs_bit-docs-html-canjs](https://cloud.githubusercontent.com/assets/78602/19332220/acfe4136-90af-11e6-814e-32bf94c2743d.png)

And broken most places in the TodMVC example.

**Comment by justinbmeyer** [comment]
Related: #115

**Comment by garrettreed** [comment]
Fixed: https://github.com/canjs/bit-docs-html-canjs/pull/134

**Comment by justinbmeyer** [comment]
confirmed!
