### ISSUE TITLE
Odd errors:

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#141]
Some path must be messed up. `stealconfig.js` is a steal thing, probably not being used by github.io.

![select_multiple_](https://cloud.githubusercontent.com/assets/78602/19332365/e86e627c-90b0-11e6-863d-318ffde4d83c.png)

**Comment by garrettreed** [comment]
@justinbmeyer how can I replicate this? I'm not seeing any errors like these - just some stuff from the twitter widget.
