### ISSUE TITLE
Add source links

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#146]
It will be very nice to make source links work again.  

To do this, we're going to want to link to the source in the specific version.  We can get that from `package.json`.  However, not every "docObject" has `package.json`.

One solution might be to "read up" parents to find one with `package` information that represents the current package.  Using that and the current `docObject''s`src`, it should be possible to get the location of the comment.

**Comment by garrettreed** [comment]
@justinbmeyer I've already implemented the first solution for getting the npm version and github stars for the article: https://github.com/canjs/bit-docs-html-canjs/pull/145

**Comment by justinbmeyer** [comment]
@garrettreed only the main package page should have `npm` and `github`.  Source should exist for every docObject.

**Comment by garrettreed** [comment]
Cool, I'll make that change.
