### ISSUE TITLE
Implement switching to 2.3 site.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#147]
Related to: https://github.com/canjs/bit-docs-html-canjs/issues/120

Make it possible to switch to 2.3.

**Comment by garrettreed** [comment]
@justinbmeyer what was the reason for returning this to in-progress?

**Comment by justinbmeyer** [comment]
I don't know.

**Comment by justinbmeyer** [comment]
Oh, it was to make it configurable probably.  I assume it is?

**Comment by garrettreed** [comment]
Yep, that was done here: https://github.com/canjs/bit-docs-html-canjs/pull/152. Thanks!
