### ISSUE TITLE
Refresh scroll position breaks

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#154]
Go to http://localhost:8080/canjs/doc/guides/todomvc.html#Createtodos

and hit refresh.  I'm currently scrolled to here:

![canjs_-_todomvc_guide_and_docs_improvements_ _issue__167_ _canjs_can-connect](https://cloud.githubusercontent.com/assets/78602/19577583/7979b67c-96dd-11e6-9698-cd870495633f.png)

Create Todos is just below this.

**Comment by garrettreed** [comment]
Fixed for the most part in this PR: https://github.com/canjs/bit-docs-html-canjs/pull/160/files

It waits until the dynamic content is loaded to scroll. Sometimes the content within the jsbins cause the iframe to expand a bit after load. In these cases, the scroll might be a little off. Here's an example of this:

![sdf](https://cloud.githubusercontent.com/assets/4079858/19660869/85cf7f0e-99ff-11e6-9eef-b7fee2f9cc83.gif)
