### ISSUE TITLE
Remove "On this page" when there's only one item?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#156]
<img width="1427" alt="canjs_-_listdata" src="https://cloud.githubusercontent.com/assets/78602/19616288/85bda43c-97d4-11e6-8545-93978efb205b.png">

Feels a little unnecessary in these situations.

**Comment by garrettreed** [comment]
Do you mean the On This Page dropdown? Or the Table of Contents?
