### ISSUE TITLE
Spacing when there's no github / npm links

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#157]
<img width="1427" alt="canjs_-_listdata" src="https://cloud.githubusercontent.com/assets/78602/19616293/af5776f6-97d4-11e6-914c-775f733b039c.png">

The spacing here feels a little much when there's no github / npm buttons.

**Comment by garrettreed** [comment]
Removing the bottom margin from this cleans it up a bit. Let me know if this is enough of a reduction:

![screen shot 2016-10-24 at 3 27 30 pm](https://cloud.githubusercontent.com/assets/4079858/19660606/828b326c-99fe-11e6-99b9-45bd9f7eb7c1.png)

![screen shot 2016-10-24 at 3 26 59 pm](https://cloud.githubusercontent.com/assets/4079858/19660620/8dc0220a-99fe-11e6-878e-63385278aca2.png)
