### ISSUE TITLE
Code elements "lower" than surrounding paragraph text. 

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#158]
<img width="627" alt="canjs_-_getlistdata" src="https://cloud.githubusercontent.com/assets/78602/19616327/c81484b2-97d5-11e6-9a16-b70b21914adc.png">

`{Set}` seems visually lower than **1. set** and A object. `{Promise<ListData>}` seems this way too.

**Comment by tomgreever** [comment]
Justin, I'm having difficulty reproducing or fixing this. But I see it too. 

However, both the `<p>` and the `<code>` elements have the same font-size + line-height. There may be slight differences in the font. 

Either way, when I zoom in on it in Photoshop, both appear to have identical baselines. 
![screen shot 2016-11-18 at 3 17 34 pm](https://cloud.githubusercontent.com/assets/326843/20447016/28c01b00-ada2-11e6-8d6d-4088f3031130.png)

But also, GitHub appears to suffer from the same visual anomaly: 
![screen shot 2016-11-18 at 3 18 18 pm](https://cloud.githubusercontent.com/assets/326843/20447036/4e6c482e-ada2-11e6-8713-189352029d61.png)
![screen shot 2016-11-18 at 3 19 39 pm](https://cloud.githubusercontent.com/assets/326843/20447064/73193d9e-ada2-11e6-9dec-432ff9605f59.png)

So I believe this is just the brackets themselves and not the fonts. I recommend closing this, unless you have a suggestion or a better way of identifying the problem.
