### ISSUE TITLE
clicking a link should not bring back the top navigation

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#164]
When someone goes from one page to the next, it's distracting that the top navigation (the part with CanJS and the social links) comes back.  

I think we should not bring this back.

If we need a way for people to "scroll up" ... I suggest adding a tiny bit of padding at the top of the content, leaving room for them to scroll up, but allowing the new content to visually be in the right place and also not have the top navigation.

**Comment by garrettreed** [comment]
@justinbmeyer this gets really tricky when articles aren't long enough to have a scrollbar. Let me know if you have any ideas. Otherwise I'll keep hacking at it.

**Comment by justinbmeyer** [comment]
can you use the scrollHeight vs offsetHeight?
