### ISSUE TITLE
deprecated warning styles

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#17]
![localhost_8080_bit-docs-html-canjs_temp_can-connect_base_base_idprop_html_and_ _can-connect_tests](https://cloud.githubusercontent.com/assets/78602/16631203/a3986e06-4383-11e6-9e64-306902663b41.png)

**Comment by tomgreever** [comment]
@justinbmeyer do you mean that the word "Depreciated 0.5.3" need to look more like a warning? Like yellow or red or something? Maybe an icon?

**Comment by tomgreever** [comment]
For example: 
![screen shot 2016-07-12 at 2 41 25 pm](https://cloud.githubusercontent.com/assets/326843/16780993/badf6a28-483e-11e6-8372-d08a191eed3b.png)

**Comment by justinbmeyer** [comment]
Yes, it should look like a warning.
