### ISSUE TITLE
Link spacing in modules descriptions

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#170]
On the homepage.

![canjs](https://cloud.githubusercontent.com/assets/78602/19772711/a78f1aa8-9c2c-11e6-991b-7f6d41b5203a.png)

**Comment by garrettreed** [comment]
There's definitely a problem here with how bit-docs-generate-html creates absolute links with the `[]` syntax. Might be the reason for the lack of space.

![screen shot 2016-10-27 at 12 12 53 pm](https://cloud.githubusercontent.com/assets/4079858/19775549/c46f284a-9c3e-11e6-98a8-1a24677061f1.png)
