### ISSUE TITLE
404 page loading

### ISSUE THREAD

**Issue by moschel** [canjs/bit-docs-html-canjs#172]
I get a 404 page when I'm clicking around the site occasionally. To reproduce:

1. Go to the homepage
1. Reload (I suspect it's something that happens before the JavaScript has fully loaded?)
1. Quickly double click Guides

It loads this page - http://canjs.github.io/canjs/doc/doc/doc/guides.html - which brings up a 404.

![clip](https://cloud.githubusercontent.com/assets/22180/19777594/8fd30692-9c3e-11e6-9764-0f1590144199.gif)

**Comment by garrettreed** [comment]
#175 should resolve this issue, but can't replicate it locally. Will need to be deployed and checked before closing.
