### ISSUE TITLE
'On this page' toolbar menu not closing on iPad 

### ISSUE THREAD

**Issue by marshallswain** [canjs/bit-docs-html-canjs#176]
![img_0697](https://cloud.githubusercontent.com/assets/128857/19792035/fb1d9094-9c83-11e6-92fc-d7021b337023.PNG)

**Comment by garrettreed** [comment]
@justinbmeyer should I go ahead with a touch-supported solution to this? Or just hide on touch devices?

**Comment by garrettreed** [comment]
Removing the dropdown on touch devices for now.
