### ISSUE TITLE
Reloading with hash doesn't scroll

### ISSUE THREAD

**Issue by moschel** [canjs/bit-docs-html-canjs#185]
1. Load a page, like http://v3.canjs.com/doc/guides/atm.html
2. Click on a table of contents link, like `5. Card model`
3. Notice it scrolls to the right part of the page
4. Reload, or load this URL in another browser http://v3.canjs.com/doc/guides/atm.html#Cardmodel

Expected: it should reload and scroll to the same section
Reality: it just reloads, but doesn't scroll

**Comment by garrettreed** [comment]
This is working in development. Will be fixed on next release.
