### ISSUE TITLE
Back button with hash doesn't work

### ISSUE THREAD

**Issue by moschel** [canjs/bit-docs-html-canjs#186]
1. Go to http://v3.canjs.com/doc/guides/todomvc.html
2. Click Setup in the table of contents
3. Now scroll back up and click the link for can-fixture
4. Now click back

Expected: the TodoMVC guide should load
Reality: The back button doesn't work, nothing happens

![clip](https://cloud.githubusercontent.com/assets/22180/19958101/58e87a3c-a16a-11e6-8742-af9dd949fd7f.gif)

Back button only breaks if the previous link has a hash in the URL

**Comment by garrettreed** [comment]
Also working in development. Will be fixed on next release.

![nav](https://cloud.githubusercontent.com/assets/4079858/19974836/3b5b91ce-a1c0-11e6-8134-1356198a7f93.gif)
