### ISSUE TITLE
Fix package.json references to bit-docs-prettify

### ISSUE THREAD

**Issue by mickmcgrath13** [canjs/bit-docs-html-canjs#188]
* https://github.com/canjs/bit-docs-html-canjs/blob/master/package.json#L17
* https://github.com/canjs/bit-docs-html-canjs/blob/master/package.json#L25
* https://github.com/canjs/bit-docs-html-canjs/blob/master/package.json#L27

**Comment by Rlin415** [comment]
Fixed
