### ISSUE TITLE
Fix bug with <p> inside Parameters / Returns

### ISSUE THREAD

**Issue by tomgreever** [canjs/bit-docs-html-canjs#19]
I assume it's a bug, but currently parameters and returns print `<p>` tags around each element resulting in the content going on multiple lines like this: 
<img width="207" alt="screen shot 2016-07-12 at 1 39 14 pm" src="https://cloud.githubusercontent.com/assets/326843/16778983/0dfae81c-4836-11e6-8221-5b2df801f0ce.png">

I worked around it in parameters by changing these p tags to inline with CSS, but that's really bad, imo. 
<img width="648" alt="screen shot 2016-07-12 at 1 40 05 pm" src="https://cloud.githubusercontent.com/assets/326843/16779016/2bb60b34-4836-11e6-95ee-2a3fd0e4b19a.png">

It would be best to prevent bit-docs from adding HTML at all so we can control it with the templates / CSS.

**Comment by justinbmeyer** [comment]
@tomgreever 


> It would be best to prevent bit-docs from adding HTML at all so we can control it with the templates / CSS.

Not really possible. Has to be the css fix.

Closing for: #34

**Comment by tomgreever** [comment]
It's not possible to prevent it from returning P tag? Can it be changed to a different tag?

**Comment by tomgreever** [comment]
One of the issues with DocumentJS is that it adds HTML we can't control. So if bitdocs is also going to add HTML, I'd like to understand a bit more. I personally think it would be better for a static site generator to not get involved in the markup, other than using the templates. Anyway, we can talk about it another time.

**Comment by justinbmeyer** [comment]
It's because we use a markdown converter. That converter wraps everything with a paragraph. If we want people writing markdown, this comes with it.

**Comment by justinbmeyer** [comment]
It's not if we want to support markdown in the Params and return descriptions (which I want to do) or we write our own markdown converter, or post-process the markdown output.

**Comment by tomgreever** [comment]
Ok, I see. That makes sense. It might be worth considering post-processing the output and removing those tags for a few things. Definitely not a priority. Thanks for the explanation.
