### ISSUE TITLE
Updates to On This Page CSS

### ISSUE THREAD

**Issue by tomgreever** [canjs/bit-docs-html-canjs#197]
https://github.com/canjs/bit-docs-html-canjs/issues/87 mentioned moving the caret triangle of the menu to the center, however I think it will look strange for the caret to be centered on the menu while the "On this page" also has a down arrow indicator. Also, this is inconsistent with the "version" menu which does not have a caret. 

This issue is to standardize these menus and refactor the code to accommodate that. This may involve a slight redesign for the menus to look more like this (incomplete): 
![screen shot 2016-11-18 at 3 09 00 pm](https://cloud.githubusercontent.com/assets/326843/20446778/fb17e698-ada0-11e6-83f1-c7ab173e29dd.png)

This will involve: 
- [x] Refactoring the menu so the `<a>` has the padding and `<li>` is just the wrapper
- [x] Separating the `/` as an individual `li`
- [x] Reversing out the background when selected
- [x] Removing the caret triangle altogether
- [x] Using standard borders, backgrounds, and drop shadows for the menu

**Comment by jamiemccue** [comment]
@chasenlehara @tomgreever Before I create a pull request for this one. Take a look at the hover state screenshot and let me know if that's what you had in mind according to the example above?

<img width="469" alt="screen shot 2017-05-23 at 3 18 42 pm" src="https://cloud.githubusercontent.com/assets/381138/26378913/614acca2-3fcb-11e7-9e75-dff33713d008.png">

<img width="509" alt="screen shot 2017-05-23 at 3 20 18 pm" src="https://cloud.githubusercontent.com/assets/381138/26378914/614e4454-3fcb-11e7-91cb-612a4f50dc1e.png">

**Comment by jamiemccue** [comment]
issue complete
