### ISSUE TITLE
Basic navigation on iPad only works for a few clicks.

### ISSUE THREAD

**Issue by marshallswain** [canjs/bit-docs-html-canjs#200]
After clicking on a couple of pages, there are two bugs that show up on my iPad Pro.  Scrolling becomes buggy so that the main content won't scroll at all or into scrolls about one line of text then stops even though my finger keeps moving.

The other bug is that links stop working until after a refresh.

**Comment by chasenlehara** [comment]
I’m having a hard time coming up with exact steps to reproduce for this issue. I can most frequently reproduce it on iPhone by going to a page on the site, scrolling, then trying to go to another page.

**Comment by justinbmeyer** [comment]
what if you slow down your internet speed?

**Comment by chasenlehara** [comment]
Throttling the network speed doesn’t seem to make this any more reproducible.

**Comment by chasenlehara** [comment]
I think part of the scroll jankiness comes from the sticky header, which I’d like to remove as part of https://github.com/canjs/bit-docs-html-canjs/issues/202. We can keep the breadcrumb inline with the page but make the “on this page” navigation in a container on the right, MDN-style.

**Comment by pYr0x** [comment]
I have the same issue on my iPad

**Comment by marshallswain** [comment]
All it takes for me to replicate the issue is to go to a page, scroll up and down, then switch pages and scroll a couple more times.

**Comment by chasenlehara** [comment]
Ok, I can pretty easily reproduce this on iPad now by just going to the home page, scrolling to the bottom, then trying to go to any other page.

**Comment by chasenlehara** [comment]
This is the error that occurs in Safari: `SecurityError (DOM Exception 18): Attempt to use history.pushState() more than 100 times per 30.000000 seconds`

The code: https://github.com/canjs/bit-docs-html-canjs/blob/40c1756bf5247d2a5507b348f1b5616dfc391008/static/canjs.js#L41-L47

Turns out this can happen on desktop Safari too.
