### ISSUE TITLE
Typo in the can-cid module description

### ISSUE THREAD

**Issue by marshallswain** [canjs/bit-docs-html-canjs#207]
<img width="1366" alt="img_0704" src="https://cloud.githubusercontent.com/assets/128857/21337442/7e31e910-c62a-11e6-9935-5bc239054e02.PNG">

**Comment by justinbmeyer** [comment]
This is an issue for canjs/canjs.  This repo is for the theme/functionality of the canjs site.  Can you open an issue there and close this one?

**Comment by marshallswain** [comment]
Issue moved to [canjs/canjs #2917](https://github.com/canjs/canjs/issues/2917) via [**ZenHub**](https://www.zenhub.com/)
