### ISSUE TITLE
The left-hand navigation’s width is not restricted

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#209]
The width of the left-hand navigation is not limited, so some pages are poorly formatted: http://canjs.com/doc/can-util/dom/events/make-mutation-event/make-mutation-event.html
<img width="1440" alt="screen shot 2016-12-23 at 8 50 25 pm" src="https://cloud.githubusercontent.com/assets/10070176/21465288/b23dae68-c951-11e6-93d7-c8b9ceff2633.png">

**Comment by justinbmeyer** [comment]
This is a bug with how those titles are created. Not with the lack of width restriction. I'll fix it because I probably created this bug.
