### ISSUE TITLE
Add an indicator when a new page is being loaded

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#212]
Because we use AJAX to load each page’s content after the first page load, we don’t get all of the browser’s standard indicators that a new page is being loaded. This is particularly bad on mobile, where it might take longer to load the page, so it’s unclear whether anything is loading or not.

**Comment by chasenlehara** [comment]
Interesting research that shows that “[p]rogress bars with animated ribbing that move backwards in a decelerating manner proved to have the strongest effect”: http://dl.acm.org/citation.cfm?id=1753556

**Comment by chasenlehara** [comment]
The PR that’s open for this has [a problem](https://github.com/canjs/bit-docs-html-canjs/pull/220#issuecomment-290871361) that makes me think it might be worth us to build our own instead of using a separate dependency. We trap push state, so we know when someone has clicked and we know when the page has finished. After that, we just need to show an effective progress animation.

**Comment by imaustink** [comment]
@chasenlehara did you want me to start working on this again? I think I could get it done pretty fast. Here's a JSFiddle I was working on before you put it on hold: https://jsfiddle.net/AustinJKurpuis/bzbckvyj/2/

**Comment by chasenlehara** [comment]
I’m hoping a designer will look at this issue next week, so let’s hold off for now.

**Comment by imaustink** [comment]
Sounds good.

**Comment by chasenlehara** [comment]
PR: https://github.com/canjs/bit-docs-html-canjs/pull/238

**Comment by chasenlehara** [comment]
https://github.com/canjs/bit-docs-html-canjs/pull/238
