### ISSUE TITLE
Scroll to top doesn’t work on iOS

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#213]
Steps to reproduce:
1. Load the [home page](http://canjs.com/)
2. Scroll down in the main content area
3. Tap the status bar

Expected results: main content area would scroll to the top

Actual results: nothing happens

**Comment by sarathnair** [comment]
Is there any video/screenshot to demonstrate the issue?

**Comment by chasenlehara** [comment]
Hi @sarathnair, here’s the best way I can capture the issue using the iOS Simulator:

On apple.com, scrolling down the page and then tapping the status bar will scroll you to the top of the page:
![apple](https://cloud.githubusercontent.com/assets/10070176/24174626/dcdca772-0e4e-11e7-888a-c131d8258a8a.gif)

On canjs.com, doing the same thing will not scroll you to the top of the page:
![canjs](https://cloud.githubusercontent.com/assets/10070176/24174638/f0cdc6f8-0e4e-11e7-94d2-000371df8f14.gif)

**Comment by sarathnair** [comment]
@chasenlehara Thank you for making the video. This issue is because of `-webkit-overflow-scrolling:touch`  css property. I will take a look into this. [Ref](http://stackoverflow.com/questions/14868053/webkit-overflow-scrollingtouch-and-tap-status-bar-to-scroll-to-top)

**Comment by chasenlehara** [comment]
Hi @sarathnair, have you looked into this at all? If not, I’m going to have one of my colleagues at Bitovi check it out.

**Comment by sarathnair** [comment]
@chasenlehara Sorry. I didn't get much time to look into this. You can ask someone to check it out. As explained above I strongly believe its a css issue. Thanks!

**Comment by imaustink** [comment]
The bug isn't caused by ```-webkit-overflow-scrolling: touch```, at least not by itself. Another issue is that with the current setup the body is always the height of the display. Tapping the menu bar only works if the body is larger than the display.

Fixing this would require some restructuring and I can't seem to preview changes without running the build which is very time-consuming. Would anyone know about setting up a good dev environment for this?

**Comment by chasenlehara** [comment]
Hm, let’s punt on this then because we might make design changes anyway.

**Comment by chasenlehara** [comment]
This was fixed by https://github.com/canjs/bit-docs-html-canjs/pull/513
