### ISSUE TITLE
Make can-stache/helpers/route come after `can-stache` and before `can-stache-bindings`

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#24]
![canjs_github_io_canjs_doc_can-component_prototype_view-model_html](https://cloud.githubusercontent.com/assets/78602/18053780/b51989a4-6dc6-11e6-997f-16ce703aa40e.png)

**Comment by garrettreed** [comment]
Needs fix: don't sort if group sort order is specified.

**Comment by justinbmeyer** [comment]
This is broken again:

![canjs_-_core](https://cloud.githubusercontent.com/assets/78602/19623789/8ff0109e-98a0-11e6-8628-11ef2ade7b23.png)
