### ISSUE TITLE
In-page search sometimes disappears in Chrome

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#254]
Sometimes in Chrome (I’m using 58 but I’ve seen this in previous versions), the in-page search disappears, making it difficult to go through all of the results. This doesn’t seem to happen in the smaller layout (when the black bar is gone) or in Safari.

See the bug in this gif:
![canjs in-page search bug](https://cloud.githubusercontent.com/assets/10070176/26366209/0656de70-3f9f-11e7-83c9-69f26968b26c.gif)

**Comment by imaustink** [comment]
@chasenlehara [this](https://github.com/canjs/bit-docs-html-canjs/blob/master/static/canjs.js#L54) seems to be causing the problem. Anytime you call `history.replaceState()`, the search box hides itself as if the page has reloaded. Is it acceptable to remove this functionality or do you perhaps have another idea?

**Comment by chasenlehara** [comment]
I’d like to fully understand exactly what functionality that code provides, but let’s continue working on this after the other design changes.

**Comment by christopherjbaker** [comment]
I tested the example in the gif above in chrome 64 and it did not experience this issue. It could an update to the browser or a change in the code. Either way, I would propose we close this (evergreen browsers and whatnot).

**Comment by chasenlehara** [comment]
I can confirm that it looks like this is fixed in Chrome 64.
