### ISSUE TITLE
'Edit on GitHub' links are broken

### ISSUE THREAD

**Issue by nlundquist** [canjs/bit-docs-html-canjs#255]
Many of our documentation pages have incorrect paths for the 'Edit on GitHub' links. See the links on:
https://canjs.com/doc/can-param.html
https://canjs.com/doc/can-cid.html
https://canjs.com/doc/can-deparam.html
and many others...

These pages cannot correctly look up what repository they belong to, and end up making paths as if they belonged to the `canjs` repo. The cause of this is missing `@package` tags in the documentation pages for these repositories. This is why a page like http://localhost:8080/doc/can-construct.html has a working link, while those above do not.

Additionally, though not broken on the active website, the docs that are built when running `npm run document` on the head of the `canjs` repo also have broken links for pages like:
/doc/can-infrastructure.html
/doc/can-core.html
/doc/api.html
and the other children of the 'API Docs' page.

Again, pages incorrectly look up what repository they belong to. This time the cause is that `can-api.md` has a `@package` tag when it should not. The helper that looks up what repo a page belongs to expects the `@package` tag to only occur in the documentation page that is named the same as the repository. 

Removing the `@package` tag from `can-api.md` fixes the links in the pages above, though it's unclear if that is the correct solution, or if we should change how this link path is calculated altogether and fix both problems at the same time.

Note: the button to GitHub star the CanJS repo that is on the `API Docs` page is also broken for the same reason

**Comment by chasenlehara** [comment]
Reassigned this to @nlundquist because during standup he said he’d take a look at it.

FYI this PR is open and related: https://github.com/canjs/bit-docs-html-canjs/pull/232

**Comment by imaustink** [comment]
@nlundquist Looks like @chasenlehara beat me to it, I was gonna mention that PR. From what I could deduce by clicking on about 30 different edit links, It appeared to fix the problem. Your report makes me think I might have missed something and the problem might be more complex than I first thought. I just had the idea to run a 404 checker on a local version to test the fix more thoroughly. I will try that when I get a chance and update my PR with the findings.

**Comment by nlundquist** [comment]
@imaustink I just tried with your PR but the links on the pages I've mentioned still seem broken for example, the edit link on can-param now looks like `http://github.com/canjs/api/edit/master//can-param.md`

I think you were on the right track but didn't quite fix the issue entirely.

**Comment by nlundquist** [comment]
I've opened a PR with my solution. Fixes both these problems by not using the closest parent page with a `@package` tag to determine the repo name. Instead we assume the page repository name is either the same as the NPM module name in the path to the page, or if the page is not inside node_modules, the repository name is 'canjs'.
