### ISSUE TITLE
Markdown shown in search previews

### ISSUE THREAD

**Issue by imaustink** [canjs/bit-docs-html-canjs#264]
See `__testing__` bellow the `ATM Guide` result.

![simulator screen shot may 24 2017 3 26 25 pm](https://cloud.githubusercontent.com/assets/6282922/26428223/659a1978-4095-11e7-87a7-ebba517eb3e1.png)

Justin suggests fixing this similar to how it's handled for `title` attributes.

![cursor_and_canjs_-_atm_guide](https://cloud.githubusercontent.com/assets/78602/26428463/754593cc-40a7-11e7-8abf-869b3810d324.png)

**Comment by mickmcgrath13** [comment]
https://github.com/bit-docs/bit-docs-generate-searchmap/blob/master/generators/search-map.js#L31

**Comment by imaustink** [comment]
Solved by https://github.com/bit-docs/bit-docs-generate-searchmap/issues/4
