### ISSUE TITLE
When arrowing down through results, the active result should be "stuck" to the bottom

### ISSUE THREAD

**Issue by imaustink** [canjs/bit-docs-html-canjs#276]
![canjs_search_highlight_keyboard](https://cloud.githubusercontent.com/assets/6282922/26611686/a27f4baa-4564-11e7-8499-706bbbada785.gif)

**Comment by chasenlehara** [comment]
I think it’d be nicer if it worked something like this:
![macos finder scrolling](https://cloud.githubusercontent.com/assets/10070176/26612100/786ba3f6-4567-11e7-8e81-ad48cd8df8a2.gif)
