### ISSUE TITLE
Navbar Overflow is not Hidden

### ISSUE THREAD

**Issue by leoj3n** [canjs/bit-docs-html-canjs#318]
On a page, in this case <https://canjs.com/doc/can-component.html>, the navbar overflow is not hidden:

![overflow-not-hidden](https://user-images.githubusercontent.com/990216/27057350-6ea16390-4f91-11e7-9556-6cc3821546af.gif)

**Comment by chasenlehara** [comment]
HI @leoj3n, I can’t seem to reproduce this. Could you provide exact steps and browser info please?

**Comment by justinbmeyer** [comment]
@leoj3n what browser / version?

**Comment by leoj3n** [comment]
I'm on Canary.

Noticed on this version:

![screen shot 2017-06-12 at 6 23 31 pm](https://user-images.githubusercontent.com/990216/27059530-938992a8-4f9c-11e7-8fee-674612d0d837.png)

Had upgrade available, and it still happens on this version:

![screen shot 2017-06-12 at 6 24 55 pm](https://user-images.githubusercontent.com/990216/27059539-a0e4ebf0-4f9c-11e7-86d7-6ccc2b1d4588.png)

I guess since I'm on canary it's probably a flexbox bug in canary or something?

**Comment by chasenlehara** [comment]
The released version of Chrome 61 doesn’t have this issue.
