### ISSUE TITLE
Images in social buttons not linked

### ISSUE THREAD

**Issue by andreaalmeida** [canjs/bit-docs-html-canjs#33]
The twitter and gitbhub button images are not linking on mobile view.  
You can find them here: https://github.com/canjs/bit-docs-html-canjs/tree/master/images

<img width="502" alt="screen shot 2016-09-07 at 3 27 23 pm" src="https://cloud.githubusercontent.com/assets/5323173/18325770/c342e95c-7510-11e6-9d36-742080835dbd.png">

**Comment by justinbmeyer** [comment]
Still not working everywhere ... 

![canjs](https://cloud.githubusercontent.com/assets/78602/19332313/79e13348-90b0-11e6-98c9-f755cc18f6a7.png)
