### ISSUE TITLE
v0.8.1-0 doesn’t include fixes from 0.8.1, 0.8.2, and 0.8.3

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#335]
The 0.8.1-0 release doesn’t have these changes from earlier versions: https://github.com/canjs/bit-docs-html-canjs/compare/v0.8.1-0...v0.8.3

The v0.8.1-0 tag looks pretty messed up: the `doc` folder is included and it doesn’t include the commit from [this PR](https://github.com/canjs/bit-docs-html-canjs/pull/325) (which is in master). To fix this, I would recommend making a new branch from v0.8.3, cherry picking the commit from the PR, then releasing that as 0.8.4.

FYI, I [fixed an issue](https://github.com/canjs/bit-docs-html-canjs/pull/307) before deploying canjs.com a couple weeks ago, and noticed tonight that the issue was back. I’ve redeployed the site with 0.8.3 to temporarily fix the issue on the live site.

**Comment by imaustink** [comment]
@chasenlehara my bad :frowning_face: I thought 8.0.0 was the published version because it was in master. All fixed now.
