### ISSUE TITLE
Scroll nav to selected page on first page load

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#339]
As a user, I’d like the sidebar navigation to automatically be scrolled down to the page I land on when first coming to the site.

For example, if I go to https://canjs.com/doc/can-stache-converters.html, then I’d like the `can-stache-converters` module to be at the top of the sidebar navigation so I can see where I am and quickly go to other pages for that module.

**Comment by leoj3n** [comment]
Yes, noticed this as well (was going to make an issue before I saw this one):

![scroll-into-view](https://user-images.githubusercontent.com/990216/27500409-0acd9e10-582e-11e7-8431-de1307e20369.gif)

Think it'd be good if that nav location was scrolled into view.

**Comment by imaustink** [comment]
@leoj3n: https://github.com/canjs/bit-docs-html-canjs/pull/348

**Comment by leoj3n** [comment]
@imaustink Sorry, didn't see that 😉 🔨

**Comment by chasenlehara** [comment]
This doesn’t seem to be working for me in Chrome or Safari on macOS.
