### ISSUE TITLE
Add titles to navigation

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#40]
`<a title="description of what this links to"/>`

**Comment by garrettreed** [comment]
Added to bit-docs here: https://github.com/bit-docs/bit-docs-generate-html/pull/6

**Comment by garrettreed** [comment]
Added helper and use for sidebar links https://github.com/canjs/bit-docs-html-canjs/commit/3c54596fe8d1b67b0e8d752f6c5cf11dd0916576.
