### ISSUE TITLE
Menu button goes over logo at smaller widths

### ISSUE THREAD

**Issue by Sinjhin** [canjs/bit-docs-html-canjs#43]
![screen shot 2016-09-17 at 12 45 19 am](https://cloud.githubusercontent.com/assets/1085104/18611324/fb3d518e-7cfa-11e6-9113-d4cda16b29da.png)

Also padding on the breadcrumb class is a bit off at these resolutions

**Comment by garrettreed** [comment]
Fixed in mobile design.
