### ISSUE TITLE
Escape HTML elements within link tags

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#460]
Problem is explained here: https://forums.donejs.com/t/why-is-can-component-content-in-component-md-invisible-in-can-component-html/902/3

In short, a docObject like:

```
@ANYTHING the/identifier <element-name>
```

When linked to like:

```
[the/identifier]
```

Will insert `<element-name>` unescaped, making it invisible.

**Comment by justinbmeyer** [comment]
The fix is to make sure all titles are HTML escaped.

**Comment by justinbmeyer** [comment]
link-text here should be updated: https://github.com/bit-docs/bit-docs-generate-html/blob/155ac94b37c913ed84c46f886d30010213a2c7e7/build/make_default_helpers.js#L285

**Comment by chasenlehara** [comment]
I think this is fixed in [bit-docs-generate-html@0.11.0](https://github.com/bit-docs/bit-docs-generate-html/releases/tag/v0.11.0)
