### ISSUE TITLE
CanJS Homepage Redesign

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#480]
## Goal   

1. Redesign the CanJS homepage to _convert*_ more new users.
2. Define the purpose of CanJS and why people should use it.

## Discovery 

There are several questions that would be good to answer:

- How do decisions get made in selecting a framework?
- How do people come to learn about CanJS?
- What messaging is worth moving users to _convert_.

We will either assume answers or perform studies to figure out these answers.

### How do decisions get made in selecting a framework?

In order, I believe that people make decisions based on:

1. Popularity ... are other people using it, was it successful for them.
2. Ease of use ... does it solve the problem at hand quickly.
3. Technical ... does it have some technically valuable feature.

### How do people come to learn about CanJS

- news/meetups
- search for something (ndjson stream)
- job postings

### What messaging is worth moving users to _convert_?

By _convert_ we mean the user performs some action that gets them closer to becoming an actual user:

- Clicking a link to the CanJS homepage
- Downloading CanJS
- Watching a video
- Subscribing / following.
- Going to the getting started guide.

The plan is to:

1. Come up with multiple messaging approaches such as:
   - CRUD
   - Ergonomics
   - Consistent Productivity
   - WebComponents + React (This would require `can-element`)
  
   These approaches are currently found [here](https://docs.google.com/document/d/1NcVDFSVVlkyi82mijur8asAjUVDNPm-rxWLyy6GjFXo/edit#heading=h.dkj8eywx641w)

2. Survey messaging approaches in various formats:

   1. Plain english.  A plain english description of the framework.   This is to keep "what we are trying to communicate" distinct from "how we are communicating".
   2. A mock google search results page.  Users select the most appealing search result.
   3. A mock "tweets" page.  Tweets would have images.  Users select the most appealing tweet.
   4. A mock "homepage". 

   We will use the results of earlier steps to prune later step choices.

   Surveys will also include information to help us understand the users and their choices such as:
   - What matters most to you in selecting a framework?

   We will send the survey out to "free" places (JavaScript Chicago, LearnJS, DoneJS Chicago) and look for paid surveys too.

**Comment by chasenlehara** [comment]
I’ve started working on the homepage hero headers & subheaders and I’d like some feedback.

Scroll down to the “Hero” header in this doc (it’s a long doc, go down to almost the very bottom): https://docs.google.com/document/d/1aBBluUpLLvUMKkGYqS9-4QaqnmKpK5LkbkFIIdhp3-Y/edit

The headers and subheaders are grouped by value proposition.

What I’d like help with right now:

1) **What value props am I missing?** I wrote down a bunch in the “Our value propositions” section of the doc, then narrowed those down to what I think we could make a compelling argument for. Did I miss any that our audience would find convincing?

2) **What points about those value props am I missing?** Are there qualities about CanJS that I haven’t mentioned in the headers & subheaders yet?

Please edit the doc directly or add comments there. Your wording doesn’t have to be perfect, I’m just looking for feedback that I can refine.

---

Some context: the “Hero — Header” section of [Julian’s growth guide](https://www.julian.com/guide/growth/landing-pages) has info on the purpose of these headers & subheaders. They’re generated from value props, which you can learn more about in the “Value propositions” section of that guide.

**Comment by chasenlehara** [comment]
Here’s a new Google Doc with the outline and copy: https://docs.google.com/document/d/1_0GpyZFU7PYig1f6nupwIeN6lndHStlMen-hhPg7c8U/edit?usp=sharing

Everything from the “Hero” section down is what I’d like feedback on, specifically…

In the “Header/subheader pairs” section:

- Which of those headers explains CanJS best?
- Which of the subheaders sells it best?
- And overall, is this how we want to position CanJS?

In the “Features and objections” section:

- What’re the most compelling features / how would you order them differently?
- For each of the features, what’s unclear? What should be expanded on?
- What features am I missing that we should advertise?

Please feel free to make edits or leave comments on copy that needs improvement. Everything is a rough draft at this point.

**Comment by chasenlehara** [comment]
Here’s a rough prototype: https://canjs-home-page-redesign.webflow.io/

The design has a bunch of problems, so please ignore things like alignment, awkward shadows, etc. Also, the page doesn’t have links to anything, so it’s not really an interactive demo.

I need help with the following:

1. Does the text in the hero convey the main value prop that we want to sell? How can we explain CanJS and sell it better?
2. What image should we show in the hero? How can we better visualize the main value prop?
3. For each of the features listed under the social proof:
	- Is this feature worth including on the home page?
	- Any suggestions for how to word and visualize the feature better?
4. What features are missing that we should advertise?

All of the feature images are placeholders. I expect to refine them once we decide which features to include and what the main copy should say.

**Comment by matthewp** [comment]
I think the hero text is good, but none of the rest of the feature texts refer back to the CRUD aspect. So there lacks reinforcement that this is good for CRUD specifically. It says CRUD, but then shows common framework features.

**Comment by chasenlehara** [comment]
Great feedback @matthewp. I just updated the prototype with some new copy that hopefully reinforces the point made in the hero.

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/canjs/canjs/issues/4735
