### ISSUE TITLE
Improve the sidebar’s styling

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#505]
@ryangwilson, I think you started working on designs for the sidebar and I said let’s leave them for later. Well, it’s later now. 😂

Some fun cases we’ll need to consider:

## Groups in groups

“recipes” has groups under it (beginning, intermediate, etc.) and is also a grouping amongst other groups.

https://canjs.com/doc/guides/recipes.html
<img width="286" alt="Screen Shot 2019-04-23 at 4 10 26 PM" src="https://user-images.githubusercontent.com/10070176/56621727-787d4280-65e2-11e9-8d28-11fc73249994.png">

## Groups in groups of groups

can-view-callbacks has groups under it (types & methods), and is also part of the Infrastructure group, which is under the Views group.

https://canjs.com/doc/can-view-callbacks.html
<img width="259" alt="Screen Shot 2019-04-23 at 4 08 32 PM" src="https://user-images.githubusercontent.com/10070176/56621721-70bd9e00-65e2-11e9-9d18-3c3970090fa5.png">

**Comment by ryangwilson** [comment]
This was the concept we discussed around the 17th. 
![sidebar-mockup-V1](https://user-images.githubusercontent.com/4571457/56680899-2e559900-6696-11e9-81b1-881b868be697.jpg)

**Comment by ryangwilson** [comment]
Updated concepts from 4/25
![sidebar-mockup-OPT1](https://user-images.githubusercontent.com/4571457/56742796-6b2b9980-6743-11e9-9a79-17bc4e2c7207.jpg)

![sidebar-mockup-OPT2](https://user-images.githubusercontent.com/4571457/56742795-6b2b9980-6743-11e9-9f18-2006aa55f796.jpg)

![sidebar-mockup-OPT3](https://user-images.githubusercontent.com/4571457/56742794-6b2b9980-6743-11e9-8257-e2d6d2c59db8.jpg)

![sidebar-mockup-OPT3 w measurements](https://user-images.githubusercontent.com/4571457/56742793-6b2b9980-6743-11e9-9df5-8b29b61db6cf.jpg)

**Comment by ryangwilson** [comment]
![sidebar-mockup-OPT5](https://user-images.githubusercontent.com/4571457/56758322-57445f80-6764-11e9-9b67-fbe7df129ffa.jpg)

![sidebar-mockup-OPT5-units](https://user-images.githubusercontent.com/4571457/56758325-5a3f5000-6764-11e9-9747-72b739fdaead.jpg)

**Comment by ryangwilson** [comment]
10 pixel indentation of nested items
![Screen Shot 2019-04-26 at 9 12 53 AM](https://user-images.githubusercontent.com/4571457/56815560-a72c3080-680f-11e9-960a-887f05cedfbc.png)

20 pixel indentation of nested items
![Screen Shot 2019-04-26 at 9 19 13 AM](https://user-images.githubusercontent.com/4571457/56815580-b9a66a00-680f-11e9-8386-bec5be117a17.png)

Sidebar link hover example
![sidebar-hover](https://user-images.githubusercontent.com/4571457/56815992-9af4a300-6810-11e9-8327-ca29f12ecf44.gif)

**Comment by justinbmeyer** [comment]
@ryangwilson is `CORE` a bigger font than `VIEWS`?  We could probably make `core`, `infrastructure`, etc pretty small.  They aren't that important of a grouping.

**Comment by ryangwilson** [comment]
Agree. Here it is adjusted
![Screen Shot 2019-04-26 at 12 43 02 PM](https://user-images.githubusercontent.com/4571457/56823099-efa01a00-6820-11e9-85bc-d6dec84c5028.png)
