### ISSUE TITLE
Clean up the design

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#506]
- [x] Get rid of Lato

- [x] Either change the direction of the vertical shadow between the left sidebar & content, or make it a solid gray line?

- [x] Add spacing to the bottom of the left sidebar to avoid this: 
<img width="300" alt="Screen Shot 2019-04-23 at 3 45 39 PM" src="https://user-images.githubusercontent.com/10070176/56620768-e9226000-65de-11e9-94c8-23be2fa20d96.png">

- [x] Fix the dropdown at 1000px wide
<img width="572" alt="Screen Shot 2019-04-23 at 3 15 59 PM" src="https://user-images.githubusercontent.com/10070176/56620821-153de100-65df-11e9-932f-8acdc1fb1ae9.png">

- [x] Vertical alignment: make the logo, version, & links share the same baseline? [And same thing with the other stuff in the nav?]
<img width="246" alt="Screen Shot 2019-04-23 at 3 48 59 PM" src="https://user-images.githubusercontent.com/10070176/56620918-6a79f280-65df-11e9-988b-ccf81533db6b.png">

- [x] Horizontal alignment: tighten the space between the main nav links, use padding instead of margin so the link target area is bigger, & make the spacing between things more cohesive (right now it’s _30px | logo | 15px | version | 60px | nav links_ on the left and _search input | 20px | By Bitovi | 10px_ on the right)

- [ ] Make comps for what the “By Bitovi” logo would look like with black text (just By black, By gray and Bitovi black, & both black)

- [x] The X in the search input feels huge to me but it looks like it’s the same size as the magnifying glass. Maybe consider making it smaller, or less thick, or…?

- [x] Consider how we could make the hover & selected states more consistent 
<img width="134" alt="Screen Shot 2019-04-23 at 4 03 15 PM" src="https://user-images.githubusercontent.com/10070176/56621459-63ec7a80-65e1-11e9-96ce-4d995c8266e0.png">

**Comment by ryangwilson** [comment]
RE: sidebar remove shadow and add gray line
<img width="1920" alt="Screen Shot 2019-04-24 at 7 35 49 AM" src="https://user-images.githubusercontent.com/4571457/56656587-e3bb2900-6663-11e9-88d9-6ed33fcf7dad.png">

Option 2 - make sidebar background a light gray color
<img width="1920" alt="Screen Shot 2019-04-24 at 7 36 13 AM" src="https://user-images.githubusercontent.com/4571457/56656597-e87fdd00-6663-11e9-91d5-0fc4102eedb5.png">

**Comment by ryangwilson** [comment]
By Bitovi mods
![as-is](https://user-images.githubusercontent.com/4571457/56674043-5c7fac80-6687-11e9-9b9e-3078575fcfb1.png)

![all-black](https://user-images.githubusercontent.com/4571457/56674083-6bfef580-6687-11e9-8bcf-09e5575d02ef.png)

![all-gray](https://user-images.githubusercontent.com/4571457/56674109-74efc700-6687-11e9-8044-ed3ebc9de2ad.png)

![bitovi-black](https://user-images.githubusercontent.com/4571457/56674118-791be480-6687-11e9-8b45-c22316c88c23.png)

![by-black](https://user-images.githubusercontent.com/4571457/56674132-7caf6b80-6687-11e9-8655-ea045696fb8c.png)

**Comment by ryangwilson** [comment]
![Screen Shot 2019-04-24 at 1 10 47 PM](https://user-images.githubusercontent.com/4571457/56680553-7de79500-6695-11e9-943e-30438306c4b0.png)
![Screen Shot 2019-04-24 at 1 10 07 PM](https://user-images.githubusercontent.com/4571457/56680554-7e802b80-6695-11e9-8757-61fac61c4616.png)
