### ISSUE TITLE
Fix scrolling issues

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#507]
The site has a couple issues related to scrolling:

- [Scroll to top doesn’t work on iOS](https://github.com/canjs/bit-docs-html-canjs/issues/213)
- Chrome-provided search results aren’t highlighted in the scroll area

I think these are caused by how we position & size the header and content. Hopefully we can switch to a more sane way of laying things out and use `position: sticky` or something like it.

**Comment by ryangwilson** [comment]
Also:
- Taking a "full page" screenshot only scrolls the left sidebar
![screencapture-localhost-8080-doc-can-observe-push-html-2019-04-25-17_03_57](https://user-images.githubusercontent.com/4571457/56751942-2c9eda80-6755-11e9-8186-72481f5ee45b.jpg)
