### ISSUE TITLE
Figure out what to do with the “By Bitovi” dropdown on mobile

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#508]
Maybe we should put it in the menu? Should it just be a link to Bitovi.com, or should we make it tappable to open up the dropdown and see the other sites?

**Comment by jamiemccue** [comment]
Looking at this issue, I agree with you that the By Bitovi should be added to the mobile menu at the bottom, and for simplicity sake only have a link to Bitovi.com rather than all the other sites. The rationale for this is to keep the experience clean and simple.
