### ISSUE TITLE
Fix searchMap cache invalidation

### ISSUE THREAD

**Issue by nlundquist** [canjs/bit-docs-html-canjs#519]
After publishing the new "Customizing Connections" data-guide I'm able to observe a pop-in after refreshing the docs which mutates the sidebar, reverting to an older version with my guide missing:

![2019-05-13 at 10 40 36](https://user-images.githubusercontent.com/2623867/57639763-d8299680-756d-11e9-9fb9-49a0244e643b.gif)

This doesn't occur while testing locally, my guide appears as normal and the sidebar isn't mutated after a refresh.

**Comment by chasenlehara** [comment]
When the `docMap.json` changes, a new `searchMap.json` is created, which is used to construct the sidebar and for search. A `searchMapHash.json` is generated; it’s a hash of the `searchMap`. This is fetched when the page is loaded, so if the `searchMap` has changed, the `searchMapHash` should also change, so the full `searchMap` should be fetched.

From this bug report, it appears something in that process isn’t working correctly.

**Comment by nlundquist** [comment]
Chasen has re-published the same revision from his machine and it ended up working. Can't explain why this issue occurred, but closing until it arises again upon a future publish.
