### ISSUE TITLE
Scrollbar visible on canjs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#523]
https://canjs.com/doc/api.html

![image (7)](https://user-images.githubusercontent.com/78602/57885868-8db84c00-77f1-11e9-82b9-d23685412ec6.png)

overflow-y: is set to `scroll` on `#left`.  I don't think it should be set at all.  

1.  Figure out why it was set (hopefully the commit/blame tells you).
2.  Remove it.  Check browsers and make sure things look right.

**Comment by cherifGsoul** [comment]
Released as https://github.com/canjs/bit-docs-html-canjs/releases/tag/v2.5.11
