### ISSUE TITLE
Clean up the hover / copy button on the code-toolbar

### ISSUE THREAD

**Issue by jamiemccue** [canjs/bit-docs-html-canjs#551]
Make the copy button consistent on all the code-toolbar blocks.

Homepage:

<img width="392" alt="Screen Shot 2019-06-26 at 3 14 54 PM" src="https://user-images.githubusercontent.com/381138/60218795-45933d00-9825-11e9-8315-17dc9ff21b06.png">

Inside:

<img width="892" alt="Screen Shot 2019-06-26 at 3 16 28 PM" src="https://user-images.githubusercontent.com/381138/60218873-7ffcda00-9825-11e9-98fc-9bbc90135044.png">
<img width="848" alt="Screen Shot 2019-06-26 at 3 17 01 PM" src="https://user-images.githubusercontent.com/381138/60218874-7ffcda00-9825-11e9-9c5e-ec97228a5113.png">

**Comment by chasenlehara** [comment]
A couple more cases:

## Collapsed code

https://canjs.com/doc/guides/crud-beginner.html#DefiningacustomelementwithCanJS

![Screen Shot 2019-06-27 at 11 03 11 AM](https://user-images.githubusercontent.com/10070176/60289488-61e9b500-98cb-11e9-9cb4-6517f19ae168.png)

## Tabbed demos

https://canjs.com/doc/guides/technology-overview.html#ObservablesandHTMLelements

![Screen Shot 2019-06-27 at 11 06 05 AM](https://user-images.githubusercontent.com/10070176/60289624-b2f9a900-98cb-11e9-9e3b-1b2c5364fb8c.png)

**Comment by chasenlehara** [comment]
I think it’d be good to come up with a design or two that considers all three of these design elements (the copy button, the expand button, and the “Edit in your browser” button).

I think these things have been added over time so we haven’t really made them cohesive.

**Comment by chasenlehara** [comment]
Another thing I think we should change: when scrolling horizontally, the expand button moves. I don’t know if we should fix this or if the design might change for these buttons, so I’m adding it onto this issue as another thing to consider.

<img width="407" alt="Screen Shot 2019-07-01 at 11 19 03 AM" src="https://user-images.githubusercontent.com/10070176/60458457-7f808c80-9bf3-11e9-9578-c25fad2830c7.png">

**Comment by jamiemccue** [comment]
@chasenlehara 

Here are a few options for the actions.

Remove the button look of Copy, add `code` to give it more context. 

<img width="767" alt="Screen Shot 2019-07-09 at 8 43 54 AM" src="https://user-images.githubusercontent.com/381138/60906440-fc32ec80-a22b-11e9-9693-3fc3b089c47b.png">

Version without code.

<img width="873" alt="Screen Shot 2019-07-09 at 8 46 28 AM" src="https://user-images.githubusercontent.com/381138/60906442-fc32ec80-a22b-11e9-8a9c-29f99ab22a36.png">

Reduce the width of the Run in your browser button.

<img width="883" alt="Screen Shot 2019-07-09 at 8 49 15 AM" src="https://user-images.githubusercontent.com/381138/60906443-fc32ec80-a22b-11e9-8e6c-6718f1ef8916.png">

Group the actions.

![options](https://user-images.githubusercontent.com/381138/60906807-e96ce780-a22c-11e9-8da2-a38039b10f5d.png)

**Comment by jamiemccue** [comment]
@chasenlehara  Here are some updated mockups based on our review.

Using words:

![example-words-1](https://user-images.githubusercontent.com/381138/61079354-8bc8ce80-a3d7-11e9-9fce-74da24c9b782.png)

![example-words-2](https://user-images.githubusercontent.com/381138/61079375-94b9a000-a3d7-11e9-901f-d375b3aa4525.png)

Using icons:

![example-icons-1](https://user-images.githubusercontent.com/381138/61079382-9be0ae00-a3d7-11e9-8d98-c3b51b0313f2.png)

![example-icons-2](https://user-images.githubusercontent.com/381138/61079384-9d11db00-a3d7-11e9-832a-2ee5f34579a5.png)

![example-icons-3](https://user-images.githubusercontent.com/381138/61079385-9d11db00-a3d7-11e9-8d2e-ddf19e6015e4.png)

Basic with copy icon

![example-icons-4](https://user-images.githubusercontent.com/381138/61081300-b452c780-a3db-11e9-9ae1-e63439bd3fb2.png)

Example 1 line

![example-1-line](https://user-images.githubusercontent.com/381138/61082027-78b8fd00-a3dd-11e9-8c67-2a996577b385.png)

Homepage

![example-1-home](https://user-images.githubusercontent.com/381138/61082392-3ba13a80-a3de-11e9-88f1-b9c8bd1cbe91.png)

![example-1-home-2](https://user-images.githubusercontent.com/381138/61083026-8c656300-a3df-11e9-95ac-9c07cb29d2c0.png)

**Comment by chasenlehara** [comment]
I think we should head in this direction, with some changes:

![example-words-1](https://user-images.githubusercontent.com/381138/61079354-8bc8ce80-a3d7-11e9-9fce-74da24c9b782.png)

1) Keep the Copy and Run buttons together on the far right in all cases. I think it makes more sense to have those actions grouped than it does to separate them.

2) Keep the line that goes over the expand bar: <img width="67" alt="Screen Shot 2019-07-11 at 2 05 05 PM" src="https://user-images.githubusercontent.com/10070176/61085578-7490dd80-a3e5-11e9-8fc9-7fd2c6d4f292.png">

3) When there is no expand bar at the top, don’t create a bar just for the actions; overlap them over the content. It’s not common that this will happen, it’ll save vertical space, and I think it’ll make the code examples less “weighty.”

4) Given 3, make sure that the actions are readable when they’re over text. [Example](https://canjs.com/doc/guides/html.html#Passingdatatoandfromcomponents): <img width="458" alt="Screen Shot 2019-07-11 at 2 12 38 PM" src="https://user-images.githubusercontent.com/10070176/61085903-4d86db80-a3e6-11e9-8cca-f1844989df40.png">

**Comment by jamiemccue** [comment]
Here are the 2 final versions:

1. This mockup is showing the expand bar at the top. This bar will be the same height at the copy/run bar showing in 2. The expand bar will have an extra 1px border at the top. 

![example-with-expand](https://user-images.githubusercontent.com/381138/61233314-23366600-a6e5-11e9-8b6e-81777040e8a6.png)

2. This mockup is showing the standard copy/run bar which is overlapped over the code. It has a .70 opacity so you can see the code behind it. 

![example-hover-copy-bar](https://user-images.githubusercontent.com/381138/61233320-27628380-a6e5-11e9-999a-d182122ad1fa.png)

**Comment by chasenlehara** [comment]
I’m closing this in favor of https://github.com/canjs/bit-docs-html-canjs/issues/561
