### ISSUE TITLE
Typography generally

### ISSUE THREAD

**Issue by jamiemccue** [canjs/bit-docs-html-canjs#552]
Suggestions for cleaning up the typography:

~~make the h1 dark grey or black (discuss if necessary)~~

<img width="941" alt="Screen Shot 2019-06-26 at 3 11 40 PM" src="https://user-images.githubusercontent.com/381138/60219026-fc8fb880-9825-11e9-9518-a79f5f62e06b.png">

- [x] make h3-h6 headings larger and black (or blue) (these headings are too small and getting lost in the visual hierarchy)

<img width="917" alt="Screen Shot 2019-06-26 at 3 12 00 PM" src="https://user-images.githubusercontent.com/381138/60219043-0addd480-9826-11e9-9a69-55b34e37f83e.png">

- [x] reduce margin-bottom on first ordered lists

<img width="941" alt="Screen Shot 2019-06-26 at 3 11 40 PM" src="https://user-images.githubusercontent.com/381138/60219137-45e00800-9826-11e9-9ea1-f61388bce436.png">

- [x] increase margin below code blocks

<img width="892" alt="Screen Shot 2019-06-26 at 3 22 20 PM" src="https://user-images.githubusercontent.com/381138/60219152-52646080-9826-11e9-9ea1-bc8bbb585c37.png">

**Comment by justinbmeyer** [comment]
Make sure codepen and diff looks ok when playing with margins

**Comment by justinbmeyer** [comment]
We should create a style guide page
