### ISSUE TITLE
Don’t show the expand button for one line of code

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#556]
[I’m not sure if this is the right repo.]

Here’s an example:
<img width="639" alt="Screen Shot 2019-06-30 at 7 25 42 PM" src="https://user-images.githubusercontent.com/10070176/60457808-cb323680-9bf1-11e9-9f94-bfa1cc9de239.png">

It seems like we should not collapse the code when only one line needs to be collapsed. It should look like this:
<img width="636" alt="Screen Shot 2019-06-30 at 7 25 48 PM" src="https://user-images.githubusercontent.com/10070176/60457827-dab17f80-9bf1-11e9-99f5-880f9b635c42.png">

**Comment by justinbmeyer** [comment]
The logic here gets a bit tricky. So we will show 3 lines, unless the 4th would eliminate a collapseable. But we wouldn’t do this for a 5th.
