### ISSUE TITLE
Implement the new copy & run buttons

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#561]
From: https://github.com/canjs/bit-docs-html-canjs/issues/551#issuecomment-511482975

Two rough mockups::

![example-expand](https://user-images.githubusercontent.com/381138/61392273-4abb3900-a873-11e9-9c1e-a36517be4ce3.png)

![example-hover-copy-bar](https://user-images.githubusercontent.com/381138/61237322-1454b100-a6ef-11e9-8439-56ff9618d0d2.png)

Changes:

- [ ] The current “Run in your browser” button at the bottom of demos moves to the upper right
- [ ] The style for those action buttons (copy & run) change
- [ ] Currently the action buttons only appear on hover; with [@media (hover: hover)](https://github.com/canjs/bit-docs-html-canjs/blob/d3717becc8126037e818f71c43aeb62cc14dd348/static/toc.less#L28), we should make the action buttons always appear on non-hover devices and appear on hover on devices that support hover
- [ ] The code snippets on the homepage should also change to match this new style

Specs (you can ask @jamiemccue for any more details):

- Font size: .8em
- Font color: #858585
- Hover color: #4078c0

<img width="111" alt="Screen Shot 2019-07-15 at 10 51 33 AM" src="https://user-images.githubusercontent.com/381138/61237303-0bfc7600-a6ef-11e9-9d5e-90b692ae9ec8.png">

**Comment by justinbmeyer** [comment]
Should we put a line between Copy and Run to make them appear more as individual buttons?

**Comment by jamiemccue** [comment]
I don't see them as buttons but links. Here is an example with lines. 

<img width="942" alt="Screen Shot 2019-07-17 at 9 22 01 AM" src="https://user-images.githubusercontent.com/381138/61392759-683cd280-a874-11e9-8199-2085c8a2ca7f.png">

**Comment by chasenlehara** [comment]
It looks like the new buttons aren’t showing up in the API signatures:

<img width="896" alt="Screen Shot 2019-10-29 at 4 22 32 PM" src="https://user-images.githubusercontent.com/10070176/67787394-6c2de280-fa68-11e9-8ed3-bfcf3b33eeda.png">
