### ISSUE TITLE
Search results text is obscured

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#583]
What I see in Chrome when searching for “stache”:
<img width="367" alt="Screen Shot 2019-10-28 at 12 33 56 PM" src="https://user-images.githubusercontent.com/10070176/67678893-ae2f2980-f97f-11e9-9561-f4df650fff7b.png">

**Comment by cherifGsoul** [comment]
In what version this happened?
I upload a GIF for the behavior that I have in Chrome 78.0.3904.70 .

![can-search](https://user-images.githubusercontent.com/109013/67691357-bb0f4580-f99e-11e9-8672-5b2ef68df7a5.gif)

**Comment by chasenlehara** [comment]
It looks like it happens on the home page. I tested in Chrome 77, Firefox 70, and Safari 13.
