### ISSUE TITLE
Versions and package information

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#59]
We need a way to get the version and package information of every module loaded in by canjs and canjs's own version and package information.  Then we also need a way to displaying it.

## Getting the data 

A tag like `@pacakge ../../package.json` might add the package info to that particular `docObject`.  However, it wouldn't be able to add multiple package.json's like is needed for the homepage.  But that might be ok.

## Using the data

DocumentJS has the ability to render a page but have inline mustache that can access the docMap (or maybe docObject) like:

```
@page CanJS

@body

## Core Collection

#### can-compute {{docMap["can-construct"].package.version}}
```

Ideally we could do something like this ... or using `Set Delimiter` on https://mustache.github.io/mustache.5.html, 
supply an alternate syntax allowing:

```
@page CanJS
@render {{=<% %>=}}
@body

## Core Collection

#### can-compute <%= docMap["can-construct"].package.version %>
```

This way there wont be any conflicts.

**Comment by garrettreed** [comment]
Moving to another issue, but I've pushed a [@package tag to bit-docs](https://github.com/bit-docs/bit-docs-tag-package). @justinbmeyer: I'll need your help publishing this.

**Comment by garrettreed** [comment]
Completed here: https://github.com/canjs/canjs/pull/2541
