### ISSUE TITLE
Ideas for improving the docs

### ISSUE THREAD

**Issue by chasenlehara** [canjs/bit-docs-html-canjs#6]
Here are some ideas for discussion:

![canjs github io canjs doc can define map map extend html](https://cloud.githubusercontent.com/assets/10070176/16527432/b9a86064-3f6b-11e6-903c-7beaddd359ab.png)

1. Change `can.DefineMap.extend([name,] [static,] prototype)` to `extend([name,] [static,] prototype)` and not repeating `extend` multiple times.
2. Use headers to break up the sections (Parameters, Return Value, & Usage).
3. Put the parameters into a table / columns (which could collapse for smaller screen sizes). Those docs seem like a worst-case for putting the params in a table, so I think it’d be better if the param docs were more concise and the details were put under an examples / discussion / usage header.

**Comment by justinbmeyer** [comment]
Regarding #1.  A few things to consider:

1. Differentiating between a function that might simply be called vs something that's on an object.  `extend([name,] [static,] prototype)` vs `.extend([name,] [static,] prototype)`.  The `.` implies a difference vs something that might look like `fixture()`.
1.  Differentiating between static and prototype.  Models have both a static and a prototype `.on` and `.bind` method.  Other than the contextual menu, imo, it's good to give a person something concrete if this is a static or prototype method from the title alone.  This is why jquery I suspect differentiates between things on the prototype like: `.add` [add](http://api.jquery.com/add/) vs `jQuery.trim` [trim](https://api.jquery.com/jQuery.trim/).  I think writing out the "typical alias" is a good thing for static methods.  Perhaps something like `DefineMap.on` and `.on`.

What do you mean "repeating extend multiple times"?

**Comment by chasenlehara** [comment]
Here’s what I meant about “repeating `extend` multiple times”:
![screen shot 2016-07-05 at 9 24 57 am](https://cloud.githubusercontent.com/assets/10070176/16591839/a7037f14-4292-11e6-9b13-150a8f3671e7.png)

The more I think about it, the more I think that following something like what MDN does for [static methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) and [prototype methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) would be a good idea: `DefineMap.extend` and `DefineMap.prototype.each` in our case.

I also think that jQuery does an awesome job of showing the different signatures:
![screen shot 2016-07-05 at 9 59 21 am](https://cloud.githubusercontent.com/assets/10070176/16592815/4d0418de-4297-11e6-940d-d4832276469d.png)

Were either of the above considered?

Following these ideas invalidates most of my suggestions, except for making the parameter docs more concise and moving the details into an examples / discussion / usage section.

**Comment by justinbmeyer** [comment]
Ours is modeled after jQuery.  And yes, even the version info is available.  You can see it in component's signatures: https://canjs.com/docs/can.Component.html.

We want to have one short example per signature to make the readme.md's work.
