### ISSUE TITLE
On scrolling down, hide top navigation bar.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#60]
If you scroll down where the red arrow is, the top navigation should disappear. It should re-appear if you scroll up.

<img width="1127" alt="localhost_8080_canjs_index_html" src="https://cloud.githubusercontent.com/assets/78602/18731119/9c7564ca-801f-11e6-80e6-e30ec520e7fb.png">

**Comment by garrettreed** [comment]
The functionality is added here: https://github.com/canjs/bit-docs-html-canjs/tree/60-toggle-nav-on-scroll

Hiding the nav without an duration/animation is a bit jarring. Adding a duration creates a delay between the two nav elements (see attached gif). I could work on combining the top nav and logo into a single element, which would allow a smooth animation. Let me know if you're happy with it as-is or if I should go ahead with working on this solution.

![showhide](https://cloud.githubusercontent.com/assets/4079858/18756241/2e2fcd86-80bd-11e6-815f-aaaa2c57697d.gif)
