### ISSUE TITLE
Finalize code block styles

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#64]
Related to: https://github.com/canjs/bit-docs-html-canjs/issues/62

I think it's odd that our code blocks have a rounded border if we are trying to be "brutal".  We might want to change that for signatures too.

![localhost_8080_canjs_doc_can-core_html](https://cloud.githubusercontent.com/assets/78602/18760007/cd7ee3de-80c4-11e6-8847-f6943ab2ef2e.png)

Also, do we use the best font?

**Comment by tomgreever** [comment]
![screen shot 2016-10-13 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/326843/19367766/24d02564-9162-11e6-9fe1-f1983219d7ac.png)
