### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#77]
This shouldn't be part of the theme, perhaps the theme reads it from configuration?

It also needs to work with pushstate.

**Comment by garrettreed** [comment]
Still need to add tracking code to canjs package.json:

`"googleAnalyticsTrackingCode": "UA-2302003-11"`

**Comment by garrettreed** [comment]
@justinbmeyer

**Comment by garrettreed** [comment]
@justinbmeyer everything is in place. I'll let you close the issue when verified to be working on next release. canjs.github.io will need to be added as a url to the tracking code if that's possible.
