### ISSUE TITLE
Navigation: Scroll position is not remembered

### ISSUE THREAD

**Issue by matthewp** [canjs/bit-docs-html-canjs#82]
![scroll-pos](https://cloud.githubusercontent.com/assets/361671/18876267/f298e414-8496-11e6-9069-e7a2db3fb8ef.gif)

**Comment by marshallswain** [comment]
Also, when you are going to a page for the first time, the scroll position stays at the previous page's scroll position.

**Comment by justinbmeyer** [comment]
@marshallswain I think this is fixed ... can you clear your cache and try again?

**Comment by marshallswain** [comment]
You're right, it's fixed.
