### ISSUE TITLE
Implement "On this page behavior"

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#84]
## Steps

 - [x] complete design of breadcrumb
 - [x] complete design of menu that expands from "On this page"
 - [x] complete design of in-page outline
 - [x] implement styles for breadcrumb
 - [x] implement styles for menu
 - [x] implement styles for outline
 - [x] implement behavior

## Overview

We are copying the behavior on [facebook's developers site](https://developers.facebook.com/docs/accountkit/android).

<img width="819" alt="android_-_account_kit" src="https://cloud.githubusercontent.com/assets/78602/18881845/8a4871ac-84a2-11e6-890e-6ca91cf7359a.png">

**Comment by andreaalmeida** [comment]
<h3>Screenshot of styled menu</h3>
<img width="690" alt="screen shot 2016-09-27 at 5 16 16 pm" src="https://cloud.githubusercontent.com/assets/5323173/18892112/35f98e0e-84d6-11e6-984a-fe426befb943.png">
