### ISSUE TITLE
Style Improvements TOC

### ISSUE THREAD

**Issue by andreaalmeida** [canjs/bit-docs-html-canjs#87]
![toc](https://cloud.githubusercontent.com/assets/5323173/18960364/76bf6a96-8637-11e6-8a39-c12fc1a06b04.png)
- Move TOC top arrow so that it is centered
- Increase drop shadow so that TOC stands out more

**Comment by chasenlehara** [comment]
Yes, please increase the drop shadow!

Right now the dropdown gets lost in the page:
<img width="509" alt="current" src="https://cloud.githubusercontent.com/assets/10070176/19484842/dd539db0-950d-11e6-83b4-85ae474ec2a5.png">

Increasing the shadow [from 10%](https://github.com/canjs/bit-docs-html-canjs/blob/a99c14948c1a82c092dba4a6061d06f00f1bddb1/static/breadcrumb.less#L74) to something like 50% would really help it stand out from the rest of the content:
<img width="510" alt="suggested" src="https://cloud.githubusercontent.com/assets/10070176/19484879/0d04348e-950e-11e6-8fa3-8dfc5d538fdd.png">

**Comment by tomgreever** [comment]
I've fixed the drop shadow in #196 and will open a new issue about the triangle / pointer b/c I think it can be handled differently. 

![screen shot 2016-11-18 at 2 59 59 pm](https://cloud.githubusercontent.com/assets/326843/20446592/0cc4b5c0-ada0-11e6-9a9e-c21d139b83de.png)
