### ISSUE TITLE
Changing pages does not re-initialize JSBins

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/bit-docs-html-canjs#94]
Switch between the Chat Guide and the TodoMVC Guide.  The JSBin's are left as links.

**Comment by garrettreed** [comment]
This was definitely working a few days ago. I'm 99% sure this is the result of a jsbin change. Even though we are specifying the jsbin version to use, the runner script for the embed code runs the latest (v3.39.19). Chrome is showing an insecure origins error. I believe it works on first request, but blocks subsequent requests from executing.

I've opened a jsbin issue here: https://github.com/jsbin/jsbin/issues/2898

**Comment by garrettreed** [comment]
I found a better workaround here: https://github.com/jsbin/jsbin/issues/2819
